version: '3'

services:
  web-app:
    build:
      context: ./web-app
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./web-app:/app
    ports:
      - '3000:8080'
    restart: on-failure
    container_name: web-app
  express-server:
    build:
      context: ./express-server
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    restart: on-failure
    container_name: express-server
    volumes:
      - /app/node_modules # Inside the container, don't try to override this folder, just leave as is
      - ./express-server:/app # Look at the server directory and copy everything into the app folder in the container
      - ./mosaic-volume:/var/lib/video
  ffmpeg-api:
    build:
      context: ./ffmpeg-api
      dockerfile: Dockerfile
    ports:
      - '3002:3002'
    restart: on-failure
    container_name: ffmpeg-api
    volumes:
      - /app/node_modules # Inside the container, don't try to override this folder, just leave as is
      - ./ffmpeg-api:/app # Look at the server directory and copy everything into the app folder in the container  
      - ./mosaic-volume:/var/lib/video
networks:
  default:
    external:
      name: mosaic-net



  
